urls.py
from django.conf.urls.defaults import patterns, include, url

from django.contrib import admin
from django.contrib.auth.views import login,logout
from django.conf import settings

from apps.urls import urlpatterns as apps_urlpatterns


admin.autodiscover()

urlpatterns = patterns('',
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),

    # Admin
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin_tools/', include('admin_tools.urls')),

    url(r'^login/', login, {'redirect_field_name':'next','template_name':'auth_error.html'}, name='auth_login'),
    url(r'^logout/', logout, {'next_page':'/'}, name='auth_logout'),

     #Redactor
    (r'^upload_img/$', 'views.upload_img'),
    (r'^upload_file/$', 'views.upload_file'),

)

urlpatterns += apps_urlpatterns

apps/faq/forms.py
# -*- coding: utf-8 -*-
from django import forms
from apps.faq.models import Question, Review

class QuestionForm(forms.ModelForm):
    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={
                'required':'required',
            }
        ),
        required=True
    )
    name = forms.CharField(
        required=False
    )
    question = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'required':'required',
            }
        ),
        required=True
    )

    class Meta:
        model = Question
        fields = ('name', 'email', 'question',)

class ReviewForm(forms.ModelForm):
    city = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'required':'required',
            }
        ),
        required=True
    )
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'required':'required',
            }
        ),
        required=True
    )
    text = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'required':'required',
            }
        ),
        required=True
    )

    class Meta:
        model = Review
        fields = ('name', 'city', 'text',)

apps/users/forms.py
# -*- coding: utf-8 -*-
from django import forms
from apps.users.models import Profile
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

attrs_dict = { 'class': 'required', 'required': True }


class ProfileForm(forms.ModelForm):
    id = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'required':'required',
            }
        ),
        required=True
    )
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                #'required':'required',
            }
        ),
        required=True
    )
    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
               # 'required':'required',
            }
        ),
        required=True
    )
    user__email = forms.EmailField(
        widget=forms.TextInput(
            attrs={
                #'required':'required',
            }
        ),
        required=True
    )
    phone = forms.CharField(
        widget=forms.TextInput(
            attrs={
                #'required':'required',
            }
        ),
        required=False
    )

    class Meta:
        model = Profile
        fields = ('id', 'name', 'last_name', 'user__email', 'phone',)

class RegistrationForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs=attrs_dict), label=_(u'username'))
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(attrs_dict,
                maxlength=75)), label=_(u'email address'))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs=attrs_dict, render_value=False),
                label=_(u'password'))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs=attrs_dict, render_value=False),
                label=_(u'password (again)'))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )

    def clean(self):
        cleaned_data = super(RegistrationForm, self).clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")

        if password1 != password2:
            raise forms.ValidationError("Повторите пароль верно.")

        return cleaned_data

templates/pages/block_menu.html
<ul>
    {% for menu_item in menu %}
        <li {% if current == menu_item.url or current == '/' and menu_item.url == '/catalog/' %}class="curr"{% endif %}>
            <a href="{{ menu_item.get_absolute_url }}">{{ menu_item.title }}</a>
        </li>
    {% endfor %}
</ul>

templates/pages/block_second_menu.html
{% if menu %}
    <h2>Покупателям</h2>
    <ul>
        {% for menu_item in menu %}
            <li><a href="{{ menu_item.get_absolute_url }}">{{ menu_item.title }}</a></li>
        {% endfor %}
    </ul>
{% endif %}

templates/pages/block_top_h.html
<div class="top_h">
    <div class="top_h_bg"><img src="/media/img/top_h.png" alt="" /></div>
    <span>{{ title|safe }}</span>
</div>

templates/pages/default.html
{% extends "base.html" %}

{% load thumbnail siteblocks_extras %}

{% if page.title %}
    {% block title %}
        {{ page.title }} &mdash;
    {% endblock %}
{% endif %}

{% block center_col %}
    <div class="text text_page">
        <h1>{{ page.title }}</h1>
        {{ page.content|safe }}
    </div>
{% endblock %}

templates/pages/index.html
{% extends "base.html" %}

{% load thumbnail %}

{% if page.title %}
    {% block title %}
        {{ page.title }} &mdash;
    {% endblock %}
{% endif %}

{% block center %}
    <div class="text text_page">
        {% if page.image %}
            <p>
                {% thumbnail page.image "374x252" as  small %}
                    <img src="{{ small.url }}" width="{{ small.x }}" height="{{ small.y }}" alt="" />
                {% endthumbnail %}
            </p>
        {% endif %}
        {{ page.content|safe }}
    </div>
{% endblock %}

templates/pages/page_content.html
{% if content %}
    {{ content|safe }}
{% endif %}

templates/pages/registration.html
{% extends "base.html" %}

{% load thumbnail siteblocks_extras %}

{% if page.title %}
    {% block title %}
        {{ page.title }} &mdash;
    {% endblock %}
{% endif %}

{% block center %}
    <div class="text text_page">
        <h1>{{ page.title }}</h1>
        {% if page.image %}
            <p>
                {% thumbnail page.image "374x252" as  small %}
                    <img src="{{ small.url }}" width="{{ small.x }}" height="{{ small.y }}" alt="" />
                {% endthumbnail %}
            </p>
        {% endif %}
        {{ page.content|safe }}

    </div>
    <div class="classes2">
        <ul>
            <li><a href="#members">Регистрация пилотов</a></li>
            <li><a href="#guests">Регистрация зрителей</a></li>
        </ul>
    </div>
    <div class="subpage" id="members" style="display: none;">
        <div class="text text_page">
            {{ members.content|safe }}
        </div>
        {% if block_reg %}
            {{ block_reg|safe }}
        {% endif %}
    </div>
    <div class="subpage" id="guests" style="display: none;">
        <div class="text text_page">
            {{ guests.content|safe }}
        </div>
        <form action="#guests" method="post" class="guest_form">
        {% if send %}
            <p>Приглашение отправлено на Ваш адрес электронной почты.</p>
        {% else %}
            <div class="input"><label for="id_name">ФИО</label>{{ form.name }}{{ form.name.errors }}</div>
            <div class="input"><label for="id_phone">Телефон</label>{{ form.phone }}{{ form.phone.errors }}</div>
            <div class="input"><label for="id_email">E-mail</label>{{ form.email }}{{ form.email.errors }}</div>
            <div class="check"><label for="id_parking">{{ form.parking }} Требуется автопарковка</label></div>
            <div class="input">{{ form.captcha }}{{ form.captcha.errors }}</div>
            <div class="submit"><input style="font: 12px/15px 'Arial', sans-serif;" type="submit" value="Получить приглашение" /></div>
        {% endif %}
        </form>
    </div>

{% endblock %}

templates/pages/subscr_cancel.html
{% extends "base.html" %}

{% load thumbnail siteblocks_extras %}

{% block title %}
    Отмена рассылки &mdash;
{% endblock %}

{% block center_col %}
    <div class="text text_page">
        <h1>Отмена рассылки</h1>
        {{ system_text }}
    </div>
{% endblock %}