urls.py
from django.conf.urls.defaults import patterns, include, url

from django.contrib import admin
from django.contrib.auth.views import login,logout
from django.conf import settings

from apps.urls import urlpatterns as apps_urlpatterns


admin.autodiscover()

urlpatterns = patterns('',
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),

    # Admin
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin_tools/', include('admin_tools.urls')),

    url(r'^login/', login, {'redirect_field_name':'next','template_name':'auth_error.html'}, name='auth_login'),
    url(r'^logout/', logout, {'next_page':'/'}, name='auth_logout'),

     #Redactor
    (r'^upload_img/$', 'views.upload_img'),
    (r'^upload_file/$', 'views.upload_file'),

)

urlpatterns += apps_urlpatterns

apps/orders/models.py
# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _
from django.db import models
from apps.products.models import Product, Size
from apps.users.models import Profile
import datetime
import os

class Cart(models.Model):
    profile = models.OneToOneField(Profile, verbose_name=u'Профиль', blank=True, null=True)
    create_date = models.DateTimeField(verbose_name=u'Дата создания', default=datetime.datetime.now)
    sessionid = models.CharField(max_length=50, verbose_name=u'ID сессии', blank=True, )

    class Meta:
        verbose_name = _(u'cart')
        verbose_name_plural = _(u'carts')

    def __unicode__(self):
        return u'%s - %s' % (self.sessionid, self.create_date)

    def get_products(self):
        return CartProduct.objects.select_related().filter(cart=self, is_deleted=False)

    def get_products_all(self):
        return CartProduct.objects.select_related().filter(cart=self)

    def get_products_count(self):
        count = 0
        for item in self.get_products():
            count += item.count
        return count
        #return self.get_products().count()

    def get_total(self):
        sum = 0
        for cart_product in self.cartproduct_set.select_related().filter(is_deleted=False):
            sum += cart_product.get_total()
        return sum

    def get_str_total(self):
        total = self.get_total()
        value = u'%s' % total
        try:
            if total._isinteger():
                value = u'%s' % value[:len(value) - 3]
                count = 3
            else:
                count = 6
        except AttributeError:
            return value

        if len(value) > count:
            ends = value[len(value) - count:]
            starts = value[:len(value) - count]

            return u'%s %s' % (starts, ends)
        else:
            return value


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, verbose_name=u'Корзина')
    count = models.PositiveIntegerField(default=1, verbose_name=u'Количество')
    product = models.ForeignKey(Product, verbose_name=u'Товар')
    is_deleted = models.BooleanField(verbose_name=u'удалён', default=False)

    class Meta:
        ordering = ['is_deleted','product__title']
        verbose_name = _(u'product_item')
        verbose_name_plural = _(u'product_items')

    def get_total(self):
        total = self.product.price * self.product.count * self.count
        return total

    def get_str_total(self):
        total = self.get_total()
        value = u'%s' % total
        if total._isinteger():
            value = u'%s' % value[:len(value) - 3]
            count = 3
        else:
            count = 6

        if len(value) > count:
            ends = value[len(value) - count:]
            starts = value[:len(value) - count]

            return u'%s %s' % (starts, ends)
        else:
            return value

    def __unicode__(self):
        return u'на %s руб.' % self.get_str_total()

from django.db.models.signals import post_save

def delete_old_carts(sender, instance, created, **kwargs):
    if created:
        now = datetime.datetime.now()
        day_ago30 = now - datetime.timedelta(days=30)
        carts = Cart.objects.filter(create_date__lte=day_ago30)
        if carts:
            carts.delete()

post_save.connect(delete_old_carts, sender=CartProduct)

order_carting_choices = (
    (u'moscow', u'Доставка по Москве'),
    (u'country', u'Доставка по стране'),
    (u'selfcarting', u'Самовывоз'),
    )

order_status_choices = (
    (u'processed', u'Обрабатывается'),
    (u'posted', u'Отправлен'),
    (u'delivered', u'Доставлен'),
    (u'cancelled', u'Отменен'),
    )

class Order(models.Model):
    profile = models.ForeignKey(Profile, verbose_name=u'Профиль', blank=True, null=True)
    first_name = models.CharField(max_length=100, verbose_name=u'Имя')
    last_name = models.CharField(max_length=100, verbose_name=u'фамилия')
    email = models.EmailField(verbose_name=u'E-mail',max_length=75)
    phone = models.CharField(max_length=50, verbose_name=u'телефон')

    order_carting = models.CharField(max_length=30, verbose_name=u'Тип доставки', choices=order_carting_choices, )
    order_status = models.CharField(max_length=30, verbose_name=u'Статус заказа', choices=order_status_choices, )

    city = models.CharField(max_length=50, verbose_name=u'город', blank=True)
    address = models.CharField(max_length=70, verbose_name=u'адрес', blank=True)
    index = models.CharField(max_length=50, verbose_name=u'индекс', blank=True)
    note = models.CharField(max_length=255, verbose_name=u'примечание', blank=True)

    create_date = models.DateTimeField(verbose_name=u'Дата оформления', default=datetime.datetime.now)

    class Meta:
        verbose_name = _(u'order_item')
        verbose_name_plural = _(u'order_items')
        ordering = ('-create_date',)

    def __unicode__(self):
        return u'заказ №%s' % self.id

#    def get_order_status(self):
#        if self.order_carting == 'processed':
#            result = u'Обрабатывается'
#        elif self.order_carting == 'posted':
#            result = u'Отправлен'
#        elif self.order_carting == 'delivered':
#            result = u'Доставлен'
#        elif self.order_carting == 'cancelled':
#            result = u'Отменен'
#        else:
#            result = u''
#        return result

    def get_products(self):
        return self.orderproduct_set.select_related().all()

    def get_products_count(self):
        return self.get_products().count()

    def get_total(self):
        sum = 0
        for order_product in self.orderproduct_set.select_related().all():
            sum += order_product.get_total()
        return sum

    def get_str_total(self):
        total = self.get_total()
        value = u'%s' % total
        if isinstance(total,int):
            value = u'%s' % value[:len(value) - 3]
            count = 3
        else:
            count = 6

        if len(value) > count:
            ends = value[len(value) - count:]
            starts = value[:len(value) - count]

            return u'%s %s' % (starts, ends)
        else:
            return value

    def admin_summary(self):
        return '<span>%s</span>' % self.get_str_total()

    admin_summary.allow_tags = True
    admin_summary.short_description = 'Сумма'

    def fullname(self):
        return '<span>%s %s</span>' % (self.first_name, self.last_name)

    fullname.allow_tags = True
    fullname.short_description = 'Имя'

class OrderProduct(models.Model):
    order = models.ForeignKey(Order, verbose_name=u'Заказ')
    count = models.PositiveIntegerField(default=1, verbose_name=u'Количество')
    product = models.ForeignKey(Product, verbose_name=u'Товар')
    size = models.ForeignKey(Size, verbose_name=u'размер')

    def __unicode__(self):
        return u'на сумму %s руб.' % self.get_str_total()

    class Meta:
        verbose_name = _(u'product_item')
        verbose_name_plural = _(u'product_items')

    def get_total(self):
        total = self.product.price * self.count
        return total

    def get_str_total(self):
        total = self.get_total()
        value = u'%s' % total
        if total._isinteger():
            value = u'%s' % value[:len(value) - 3]
            count = 3
        else:
            count = 6

        if len(value) > count:
            ends = value[len(value) - count:]
            starts = value[:len(value) - count]

            return u'%s %s' % (starts, ends)
        else:
            return value

class EmsCity(models.Model):
    value = models.CharField(max_length=100, verbose_name=u'Код')
    name = models.CharField(max_length=100, verbose_name=u'Название')

    def __unicode__(self):
        return self.value

    class Meta:
        verbose_name = _(u'product_item')
        verbose_name_plural = _(u'product_items')

apps/orders/forms.py
# -*- coding: utf-8 -*-
from django import forms
from apps.orders.models import Order

class RegistrationOrderForm(forms.ModelForm):
    note = forms.CharField(
        widget=forms.Textarea(),
        required=False
    )

    class Meta:
        model = Order
        exclude = ('create_date',)

    def clean(self):
        cleaned_data = super(RegistrationOrderForm, self).clean()
        order_carting = cleaned_data.get("order_carting")
        city = cleaned_data.get("city")
        address = cleaned_data.get("address")
        index = cleaned_data.get("index")

        if order_carting == 'country' and (city=='' and address=='' and index==''):
            raise forms.ValidationError("Обязательное поле.")

        return cleaned_data

templates/orders/block_cart.html
{% if is_empty %}
    <div class="cartbox">
        <div class="cartbox_empty">
            <p>Ваша корзина пока пуста</p>
            <p>Возможно, что‑то&nbsp;найдёте среди <a href="/catalog/new/">новых&nbsp;моделей</a></p>
        </div>
    </div><!--/cartbox-->
{% else %}
    <div class="cartbox">
        <div class="cartbox_full">
            <p>У Вас в корзине</p>
            <p class="cartbox_qty"><a href="/cart/">{{ cart_products_count }} {{ cart_products_text }}</a></p>
            <p>на сумму</p>
            <p class="cartbox_sum">{{ cart_total }} руб.</p>
            <div class="cartbox_lnk"><a href="/cart/">Оформить</a></div>
        </div>
    </div><!--/cartbox-->
{% endif %}

templates/orders/block_modal_to_cart.html
{% load thumbnail %}
<div class="item_page item_page_modal parent_blk">
	<h1>Добавление в заказ</h1>
	
	<div class="item_l col">
                <div class="item_img_zl">
                    {% thumbnail product.image "162x162" as im %}
                        <div class="product_img"><img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="" /></div>
                    {% endthumbnail %}
                </div>
	</div><!--/item_l-->
	
	<div class="item_r col">
            <h2>{{ product.title }} {% if product.art %}<span class="item_art">«{{ product.art }}»</span>{% endif %} </h2>

            <div class="text">
                <p>{{ product.description|safe }}</p>
            </div>

            {% if product.material %}
                <div class="item_mat"><strong>Материал:</strong> {{ product.material }}</div>
            {% endif %}
            {% if product.color %}
                <div class="item_mat"><strong>Цвет:</strong> {{ product.color }}</div>
            {% endif %}
	       {% if product.count %}
                <div class="item_mat"><strong>Количество в коробке:</strong> {{ product.count }} шт.</div>
            {% endif %}
                    
            <div class="item_note"><em>В коробке размеры от {{ product.get_min }} до {{ product.get_max }}</em></div>

            <div class="item_page_price">{{ product.get_str_price }} <span>руб.</span></div>
            <div class="item_page_price_note col">оптовая цена за штуку</div>
		
                    <div class="item_cart">
                        <table class="item_cart_table">
                            <tr>
                                <td><div class="item_cart_h">Цена <br />за&nbsp;коробку</div></td>
                                <td><div class="item_cart_h">Кол-во <br />коробок</div></td>
                                <td><div class="item_cart_h">Стоимость</div></td>
                            </tr>
                            <tr class="item_cart_line">
                                <td><div class="item_cart_price">{{ product.get_str_price_for_box }} <span>руб.</span></div></td>
                                <td>
                                    <div class="cart_qty">
                                        <div><input class="btn2 cart_qty_btn" type="button" value="1" /></div>
                                        <div class="cart_qty_modal" style="display: none;">
                                            <h3>Изменить количество</h3>
                                            <p><span class="cart_qty_price"><span>{{ product.get_str_price_for_box }}</span> руб.</span> × <input class="cart_qty_modal_text" type="text" value="1"/> = <span class="cart_qty_total_price"><span>{{ product.get_str_price_for_box }}</span> руб.</span></p>
                                            <div><input class="cart_qty_modal_ok" type="button" value="Сохранить" /> <input class="cart_qty_modal_cancel" type="button" value="Отменить" /></div>
                                        </div>
                                    </div>
                                </td>
                                <td><div class="item_cart_price"><div>{{ product.get_str_price_for_box }}</div> <span>руб.</span></div></td>
                            </tr>
                        </table>
                        <div class="item_cart_h"></div>
                    </div>
		
		<div class="item_cart_btn"><input class="btn1 buy_btn" name="{{ product.id }}" type="button" value="Купить"></div>
	</div><!--/item_r-->
</div>

templates/orders/cart_detail.html
{% extends "base.html" %}

{% load thumbnail siteblocks_extras pages_extras %}

{% block title %}
    Корзина &mdash;
{% endblock %}

{% block center_col %}
    {% block_top_h 'Ваш заказ' %}

    {% if is_empty %}
            <h1>Ваша корзина пока пуста</h1>
    {% else %}
        <div class="cart">
            <div class="cart_item_head">
                    <div class="cart_img"></div>
                    <div class="cart_des"></div>
                    <div class="cart_box col"><div class="item_cart_h">Цена <br>за&nbsp;коробку</div></div>
                    <div class="cart_qty"><div class="item_cart_h">Кол-во <br>коробок</div></div>
                    <div class="cart_price"><div class="item_cart_h">Стоимость</div></div>
                </div>
            {% for cart_item in cart_products %}
                {% include 'orders/cart_item.html' %}
            {% endfor %}

            <div class="cart_total">
                <strong>Общая стоимость</strong>
                <div class="item_price">{{ cart_str_total }} <span>руб.</span></div>
                <input type="hidden" class="id_cart" value="{{ cart_id }}">
                <div><a href="/show_order_form/"><input class="btn2 cart_submit" type="button" value="Оформить заказ" /></a></div>
            </div>
        </div><!--/cart-->
    {% endif %}
{% endblock %}

templates/orders/cart_item.html
{% load thumbnail %}
<div class="cart_item{% if cart_item.is_deleted %} cart_item_deleted{% endif %}{% if loaded %} loaded{% endif %}" {% if loaded %}style="display: none;"{% endif %}>

    {% if loaded %}
        <input type="hidden" id="cart_str_total" value="{{ cart_str_total }}">
    {% endif %}

    <div class="cart_img">
        {% thumbnail cart_item.product.image "120x120" as im %}
            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" style="margin:{{ im|margin:"120x120" }}" alt="" />
        {% endthumbnail %}
    </div>
    <div class="cart_des">
        <h3 class="item_name"><a href="{{ cart_item.product.get_absolute_url }}">{{ cart_item.product.title }}</a></h3>
            <div class="item_art">{% if cart_item.product.art %}«{{ cart_item.product.art }}»{% endif %}</div>
            <div class="item_note"><em>В коробке размеры от {{ cart_item.product.get_min }} до {{ cart_item.product.get_max }}</em></div>
    </div>
    <div class="cart_box col">
        <div class="item_cart_price">{{ cart_item.product.get_str_price_for_box }} <span>руб.</span></div>
        <div class="cart_box_qty">{{ cart_item.product.count }} шт.</div>
    </div>
    <div class="cart_qty">
        <div><input class="btn2 cart_qty_btn" type="button" value="{{ cart_item.count }}" /></div>

        <div class="cart_qty_modal" style="display: none;">
            <h3>Изменить количество</h3>
            <input type="hidden" class="initial_count" value="{{ cart_item.count }}">
            <input type="hidden" class="cart_qty_item_id" value="{{ cart_item.id }}">
            <p><span class="cart_qty_price"><span>{{ cart_item.product.get_str_price_for_box }}</span> руб.</span> × <input class="cart_qty_modal_text" type="text" value="{{ cart_item.count }}"/> = <span class="cart_qty_total_price"><span>{{ cart_item.get_str_total }}</span> руб.</span></p>
            <div><input class="cart_qty_modal_ok" type="button" value="Сохранить" /> <input class="cart_qty_modal_cancel" type="button" value="Отменить" /></div>
        </div>

    </div>
    <div class="cart_price">
        <div class="item_price">{{ cart_item.get_str_total }} <span>руб.</span></div>
        <div class="cart_price_del"><a href="#" class="delete_cart_id" rel="{{ cart_item.id }}">удалить</a></div>
    </div>

    <div class="ci_t"><img src="/media/img/ci_t.png" alt="" /></div>
    <div class="ci_r"><img src="/media/img/ci_r.png" alt="" /></div>
    <div class="ci_b"><img src="/media/img/ci_b.png" alt="" /></div>
    <div class="ci_l"><img src="/media/img/ci_l.png" alt="" /></div>

    <div class="cart_item_restore_fade" {% if not cart_item.is_deleted %}style="display: none;"{% endif %}><input class="btn2 cart_item_restore_btn" type="button" name="{{ cart_item.id }}" value="Вернуть" /></div>
</div>

templates/orders/message_template.html
<p><h2>Практичная обувь - Информация по заказу №{{ order.id }}</h2>
<p>Дата заказа: {{ order.create_date }}</p>
<p>Заказчик: {{ order.first_name }} {{ order.last_name }}</p>
<p>E-mail: {{ order.email }}</p>
<p>Телефон: {{ order.phone }}</p>
<p>Тип доставки: {% if order.order_carting == 'country' %}Доставка по стране{% endif %}{% if order.order_carting == 'moscow' %}Доставка по Москве{% endif %}{% if order.order_carting == 'selfcarting' %}Самовывоз{% endif %}</p>
{% if order.order_carting.value == 'country' %}
<hr>
    <p>Город: {{ order.city }}</p>
    <p>Адрес: {{ order.address }}</p>
    <p>Индекс: {{ order.index }}</p>
    <p>Примечание: {{ order.note }}</p>
{% endif %}
<hr>
<p>Сумма заказа: {{ order.get_str_total }} руб.</p>
<hr>
<h3>Товары:</h3>
<ul>
{% for product in products %}
    <li>{{ product.product.title }} (размер {{ product.size.value }}), в количестве {{ product.count }} шт, на сумму {{ product.get_str_total }} руб.</li>
{% endfor %}
</ul>
</p>

templates/orders/order_form.html
{% extends "base.html" %}

{% load thumbnail siteblocks_extras pages_extras %}

{% block title %}
    Оформление заказа &mdash;
{% endblock %}

{% block extend_js %}
{% endblock %}

{% block banner %}{% endblock %}

{% block center_class %} center_wide{% endblock %}

{% block center_col %}
    {% block_top_h 'Оформление заказа' %}
    {% comment %}{{ order_form.errors }}{% endcomment %}
    <form class="order_form" method="post" action="/order_form_step2/">
        <div style="display: none;">{{ order_form.profile }}
            {{ order_form.profile.errors }}
            {{ order_form.order_carting }}
            {{ order_form.order_carting.errors }}
            {{ order_form.order_status }}
            {{ order_form.order_status.errors }}</div>
        <div class="order_form_h">
            <span class="order_form_h_num">1</span>
            <h2>Контактные данные</h2>
            {% if not user.is_authenticated %}<span class="ifregistred">Уже зарегистрированы? <a href="#auth_form" class="fancybox">Войти</a></span>{% endif %}
        </div>

        <div class="input input1">
            <label>Имя <span class="label_note">Имя получателя</span></label>
            {{ order_form.first_name }}
            {{ order_form.first_name.errors }}
        </div>
        <div class="input input1">
            <label>Фамилия <span class="label_note">Фамилия получателя</span></label>
            {{ order_form.last_name }}
            {{ order_form.last_name.errors }}
        </div>
        <div class="input input1">
            <label>E-mail <span class="label_note">Для входа на сайт</span></label>
            {{ order_form.email }}
            {{ order_form.email.errors }}
        </div>
        <div class="input input1">
            <label>Телефон <span class="label_note">Для подтверждения</span></label>
            {{ order_form.phone }}
            {{ order_form.phone.errors }}
        </div>

        <div class="order_form_h">
            <span class="order_form_h_num">2</span>
            <h2>Получение товара</h2>
        </div>

        <ul class="order_menu">
            <li {% if order_form.order_carting.value == 'moscow' %}class="curr"{% endif %}><a href="#" class="moscow">Доставка по Москве</a></li>
            <li {% if order_form.order_carting.value == 'country' %}class="curr"{% endif %}><a href="#" class="country">Доставка по стране</a></li>
            <li {% if order_form.order_carting.value == 'selfcarting' %}class="curr"{% endif %}><a href="#" class="selfcarting">Самовывоз</a></li>
        </ul>

        <div class="contact_info moscow" {% if order_form.order_carting.value != 'moscow' %}style="display: none;"{% endif %}>
            <div class="input1 ems_div" style="background: #f5f2bc;padding: 6px 12px 6px 12px; margin: -10px 0px 25px 160px; width:auto;">
                Доставка: {{ carting_price_moscow.value }} руб.
            </div>
        </div>

        <div class="contact_info selfcarting" {% if order_form.order_carting.value != 'selfcarting' %}style="display: none;"{% endif %}>{{ page_selfcarting.content|safe }}</div>

        <div class="contact_info country" {% if order_form.order_carting.value != 'country' %}style="display: none;"{% endif %}>
            <div class="input input1">
                <label>Город <span class="label_note">Город доставки</span></label>
                {{ order_form.city }}
                {{ order_form.city.errors }}
                {{ order_form.non_field_errors  }}
            </div>
            <div class="input input1 input_index">
                <label>Индекс <span class="label_note">Почтовый индекс</span></label>
                {{ order_form.index }}
                {{ order_form.index.errors }}
                {{ order_form.non_field_errors  }}
            </div>
            <div class="input input2 input_address">
                <label>Адрес <span class="label_note">Улица, дом, квартира</span></label>
                {{ order_form.address }}
                {{ order_form.address.errors }}
                {{ order_form.non_field_errors  }}
            </div>
            <div class="input1 ems_div" style="display: none;background: #f5f2bc;padding: 6px 12px 6px 12px; margin: -10px 0px 25px 160px; width:auto;">
                Доставка: <span class="ems_price"></span> руб.
            </div>
            <div class="textarea textarea1 input_note">
                <label>Примечание <span class="label_note">Номер домофона или&nbsp;любая другая информация</span></label>
                {{ order_form.note }}
                {{ order_form.note.errors }}
                {{ order_form.non_field_errors  }}
            </div>
        </div>

        <div><input class="btn2 cart_submit" type="submit" name="cart_submit" value="Отправить заказ" /></div>
    </form>
{% endblock %}

{% block right_col %}
    <script type="text/javascript">
        if ($("#id_city").val()!=undefined){
            EmsPrice($("#id_city").val());
        }
    </script>
{% endblock %}

{% comment %}
{% if cart_products and form %}
    <h3>Ваш заказ</h3>
    <p>{% for product in cart_products %}
        {{ product.product.title }} - {{ product.count }}шт{% if forloop.last %}.{% else %},{% endif %}
    {% endfor %}
        На сумму <span>{{ cart_str_total }}</span> руб.</p>
    <form action="" class="order_form" method="post">
        <h3>Контактная информация</h3>
        <div class="input">{{ form.fullname }}{{ form.fullname.errors }}</div>
        <div class="input">{{ form.contact_info }}{{ form.contact_info.errors }}</div>
        <div class="submit"><div><input type="button" class="send_order" value="Завершить оформление" /></div></div>
    </form>
{% endcomment %}
{% comment %}<div class="order col">
</div><!-- /order -->{% endcomment %}{% comment %}

{% endif %}{% endcomment %}

templates/orders/order_form_final.html
{% extends "base.html" %}

{% load thumbnail siteblocks_extras pages_extras %}

{% block title %}
    Оформление заказа &mdash;
{% endblock %}

{% block center_col %}
    {% block_top_h 'Оформление заказа' %}

    <div class="order_final">
        <div class="text text_page">
            <h1>Ваш заказ успешно оформлен под номером {{ order.id }}</h1>
            <p>Вся информация о заказе выслана на контактный e-mail. Наш менеджер скоро с Вами свяжется чтобы уточнить время доставки.</p>
            {% if reg_form %}
                <p>Вы занесли уже большую часть информации, чтобы участвовать в наших акциях и специальных предложения. Мы советуем Вам зарегистрироваться на нашем сайте.</p>
            {% endif %}
        </div><!--/text-->
        {% if reg_form %}
            <form class="final_reg" method="post" action="/registration_form/">
                <div style="display: none;">
                    {{ reg_form.email }}
                    {{ reg_form.username.errors }}
                    {{ reg_form.email.errors }}
                </div>
                <div class="input input3">
                    <label>Осталось только придумать пароль:</label>
                    {{ reg_form.password1 }}
                    {{ reg_form.password1.errors }}
                </div>
                <div class="input input3">
                    <label>Повторение пароля:</label>
                    {{ reg_form.password2 }}
                    {{ reg_form.password2.errors }}
                </div>
                <input type="hidden" name="order_id" value="{{ order.id }}">
                <div><input class="btn2 reg_submit" type="submit" value="Зарегистрироваться" /></div>
            </form>
        {% endif %}
    </div><!--/order_final-->
{% endblock %}